### ISSUE TITLE
Only icon shows

### ISSUE THREAD

**Issue by booYah187** [Sispheor/indicator-ip#13]
Greetings. Trying to get this running on Ubuntu 20.04 on a pi4b and I am unable to get the address to appear on the panel, only the icon shows. I feel like I'm overlooking something very stupid, so apologies in advance if that's the case.

Best regards, 

Matt

**Comment by dragonlost** [comment]
same on xubuntu 20.04 LTS and 22.04 LTS

**Comment by Sispheor** [comment]
Package updated on Ubuntu 22.04. Should be fine.
