### ISSUE TITLE
IPs don't show in dropdown

### ISSUE THREAD

**Issue by verustech** [Sispheor/indicator-ip#17]
This is a great utility, exactly what I was looking for!

I'm on Ubuntu 20.04 LTS, fresh install.

The selected IP shows up in the System Tray, but your picture shows the dropdown showing all the IPs, mine appear blank.

![image](https://user-images.githubusercontent.com/18144292/160941863-5aa0375a-948a-481f-af7d-4a49e69559ee.png)

Is there anything I can do about this?

Thanks again!

**Comment by Sispheor** [comment]
Package updated on Ubuntu 22.04.
I close this one.
