### ISSUE TITLE
Refresh not working after enabling VPN

### ISSUE THREAD

**Issue by tvadakia** [Sispheor/indicator-ip#2]
Ubuntu 20.04 LTS / GNOME 3.36.2, Indicator-IP ran on startup

IIP works just fine on startup; however, it doesn't refresh (either automatically or manually using the "refresh" feature built into the app) after I connect to a VPN.

**Comment by kaihen5244** [comment]
I am experiencing this same issue when changing primary network connections as well. It does not refresh even when specifically using the refresh button. Using Ubuntu 20.04 LTS. Python3

**Comment by anttiraila** [comment]
I am experiencing the same issue on Ubuntu 20.04 LTS / Unity 7.5.0: indicator-ip never refreshes

**Comment by Sispheor** [comment]
It's a company vpn ? With a proxy?

**Comment by anttiraila** [comment]
It's a commercial VPN provider, with its own app (you can connect without an app, by importing configs into NetworkManager, but I failed to do that and killed my networking, so I'm using an app for now). I would very much appreciate it if you would accept some BTC so you can buy this service and try for yourself.

**Comment by Sispheor** [comment]
Fixed

**Comment by anttiraila** [comment]
After `sudo apt update` and `sudo apt install --reinstall python3-indicator-ip`, the indicator version installed on my system is still 1.1.2-1.
