### ISSUE TITLE
Indicator too wide

### ISSUE THREAD

**Issue by Trout1952** [Sispheor/indicator-ip#3]
Hi Sispheor,
Tried your version of indicator-ip on Ubuntu 20.04 LTS. Apart from it not changing value on the indicator when I change IP through VPN, the display is too wide. If I try to add it to the top indicator bar in "indicator applet complete" all the other indicators are pushed to one side and are crammed over each other. I have tried placing "indicator applet complete" on a separate panel but this messes up the desktop as there are no options to reposition the desktop folders in 20.04.
Could you please look into this? Many thanks and best wishes.

**Comment by Sispheor** [comment]
I cannot reproduce the issue on my dev env...

**Comment by Trout1952** [comment]
Hi Sispheor,
I am using Ubuntu 20.04 with Gnome Compiz Flashback.
I managed to clear everything and start again and no longer get the previous problem with crowding out other applications.
I notice that you have upgraded today and tried to install indicator-ip but perhaps it takes awhile for the servers to refresh as the version I got wouldn't update when I used VPN Secure and refreshed. Also, I see it still takes up a lot of space. As you can see there are two white vertical bars before the ip indicator and, if I left click anywhere along this line I can see refresh, lo, enp3so, wlx000f0201095b and public plus quit.
Please see picture below.
![Screenshot from 2020-10-17 14-58-38](https://user-images.githubusercontent.com/37925432/96352537-856cdc00-1089-11eb-8ffd-d6877c2f5aca.png)

Many thanks and best wishes

**Comment by minhchuvolam** [comment]
Maybe we can have an option to show only an icon in the tray instead of the whole ip.

**Comment by Sispheor** [comment]
@minhchuvolam the prob here seems that the icon doesn't appear and that make blank space.
I can't reproduce. It's ok on my side with the dev version and the package version.

**Comment by Trout1952** [comment]
OK, thank you for looking into it though.


Best wishes,

Andy






andy.turton@btinternet.com <mailto:andy.turton@btinternet.com>









------ Original Message ------

**Comment by Sispheor** [comment]
Package updated on Ubuntu 22.04.
I could not reproduce this issue.
