### ISSUE TITLE
Question: Change refresh intervall

### ISSUE THREAD

**Issue by ninjavisa** [Sispheor/indicator-ip#7]
Hi,
My app does not update at all or very seldom is it possible to increase how often the refresh is done? I would like to have it every 20 seconds, thanks

**Comment by Sispheor** [comment]
So far it's only manually. But it could be a nice feature indeed.
Fell free to send a pull request if you know how to implement it

**Comment by ninjavisa** [comment]
```
diff --git a/indicator_ip/indicator_ip_menu.py b/indicator_ip/indicator_ip_menu.py
index 5b34704..18f23a6 100644
--- a/indicator_ip/indicator_ip_menu.py
+++ b/indicator_ip/indicator_ip_menu.py
@@ -6,8 +6,7 @@ from indicator_ip.net_utils import NetUtils
 gi.require_version('Gtk', '3.0')
 gi.require_version('AppIndicator3', '0.1')
 gi.require_version('Notify', '0.7')
-from gi.repository import Gtk, AppIndicator3, Gdk, Notify
-
+from gi.repository import Gtk, AppIndicator3, Gdk, Notify, GObject
 
 class IndicatorIPMenu(object):
 
@@ -32,6 +31,8 @@ class IndicatorIPMenu(object):
 
         self.last_clicked_interface = None
 
+        GObject.timeout_add(3000, self.refresh)
+
     def create_menu(self):
         menu = Gtk.Menu()
 
@@ -72,13 +73,15 @@ class IndicatorIPMenu(object):
     def quit(_):
         Gtk.main_quit()
 
-    def refresh(self, _):
+    def refresh(self, w=None):
         # print("refresh")
         self.indicator.set_menu(self.create_menu())
         # set by default the public IP as label
         self.indicator.set_label(str(NetUtils.get_public_interface().ip),
                                  str(NetUtils.get_public_interface().ip))
 
+        GObject.timeout_add(3000, self.refresh)
+
     def on_clicked_item(self, button, interface):
         if button.get_active():
             if interface != self.last_clicked_interface or self.last_clicked_interface is None:
```

**Comment by ninjavisa** [comment]
This code worked for me

**Comment by Sispheor** [comment]
Send a PR please. Would be easier for me review.
Thanks.

**Comment by ninjavisa** [comment]
I cannot push for some unknown reason

**Comment by Sispheor** [comment]
Push? Directly in this repo? 
Of course you can't. Lol.
It's not how it work on github.
The idae is for you to fork the project, push into your fork (in a dev branch) and then Github will propose you to create a pull request.
You'll find a lot of resource online to learn. Welcome to the open source world.

**Comment by ninjavisa** [comment]
Oh I see, usually I work with private github servers. The workflow there is you create a feature branch and from that you create a pull request to the master branch

**Comment by Sispheor** [comment]
Yes that's the idea here too. But you need to do this in a fork.
You problably codded directly into the cloned version if this repo.
You need to fork, then clone your fork, update it with a feature branch and then github will propose to PR.

**Comment by ninjavisa** [comment]
Ok got it, thanks for explaining

I have created a pull request now

**Comment by Sispheor** [comment]
Done and merged
